# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name : Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish ./CurrentTimeService/CurrentTimeService.csproj -c Release -o ${{ env.DOTNET_ROOT }}/app
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: personApp-artifact
          path: ${{ env.DOTNET_ROOT }}/app
  
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Dev'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: personApp-artifact
      - name: Azure WebApp
        id: deploy-to-azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'L4mwoTimeService'
          publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: 'Prod'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: personApp-artifact
      - name: Azure WebApp
        id: deploy_to_azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'L4mwoTimeServiceProd'
          publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD }}
